sudo: false

language: node_js

node_js:
  - "0.12"

branches:
  except:
    - gh-pages

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install -g bower gulp
  - npm install